#pragma once

#include <iostream>
//#include <vector>
//#include <queue>
//#include <stack>
#include <algorithm>
//#include <cmath>
//#include <map>
//#include <set>
#include <string>
#include <cstring>
//#include <climits>
//#include <numeric>
//#include <iomanip>
//#include <functional>
//#include <unordered_map>
//#include <unordered_set>
#include <sstream>
//#include <string>